Update Web App guidelines
opencadc/.github pull request #4
Opened 2024-06-26 19:15 UTC by at88mph

2024-07-05 23:09 UTC, brianmajor requested changes
Looks great Dustin, just a few spelling suggestions.

2024-07-05 23:09 UTC, brianmajor commented on CONTRIBUTING.md
> +Our web applications span many years and are made up of many common technologies such as Vanilla JavaScript, jQuery, CSS, and HTML, but we've also, in recent years, adopted ReactJS in our [Science Po
```suggestion
Our web applications span many years and are made up of many common technologies such as vanilla JavaScript, jQuery, CSS, and HTML, but we've also, in recent years, adopted ReactJS in our [Science Portal](https://github.com/opencadc/science-portal) application.
```

2024-07-05 23:09 UTC, brianmajor commented on CONTRIBUTING.md
> +- Use Vanilla JavaScript when available
```suggestion
- Use vanilla JavaScript when available
```

2024-07-05 23:09 UTC, brianmajor commented on CONTRIBUTING.md
> +- No semi-colons at end of statement
```suggestion
- No semicolons at end of statement
```

2024-07-08 22:34 UTC, at88mph commented
Changes made.

2024-07-10 23:14 UTC, brianmajor approved these changes

2024-07-10 23:14 UTC, merged